### ISSUE TITLE
Publication Link?

### ISSUE THREAD

**Issue by arjunskumar** [PHerb-Pub/MirrEnv#1]
Is there a link where I can access the publication?

**Comment by PHerb-Pub** [comment]
Hi there,
There is not currently a publication link, but we hope there will be soon. I'll edit the page when it becomes available, and will add another comment here to let you know.
Thanks for your interest.

**Comment by PHerb-Pub** [comment]
Hi there,
The paper was published yesterday, I have updated the page to include the link to it and the dataset.

Regards
